language: python
jobs:
  include:
  - name "test1"
    python: "3.5"
    env: TEST_SUITE="suite_test1"
  - name "test2"
    python: "3.5"
    env: TEST_SUITE="suite_test2"
  - name "test3"
    python: "3.5"
    env: TEST_SUITE="suite_test3"
script: env TEST_SUITE=$TEST_SUITE ./test.py

