language: c
compiler: gcc
os: linux
# Require gettext-0.19.8
dist: focal
jobs:
  include:
  - name: "amd64"
    arch: amd64
  #- name: "ppc64le"
  #  arch: ppc64le
  #- name: "s390x"
  #  arch: s390x
  #- name: "arm64"
  #  arch: arm64
addons:
  apt:
    packages:
    # For autogen.sh
    - gnome-common
    - gtk-doc-tools
    # For make from
    # https://packages.ubuntu.com/search?searchon=sourcenames&keywords=ibus
    - autoconf
    - automake
    - autotools-dev
    - desktop-file-utils
    - gobject-introspection
    - iso-codes
    - libdbus-glib-1-dev
    - libdconf-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtk2.0-dev
    - libnotify-dev
    - libtool
    - python-gi-dev
    - python3-all
    - python3-dbus
    - valac
script:
  - git clone git://github.com/ibus/ibus.git
  - cd ibus
  - ./autogen.sh
