language: c
compiler: gcc
os: linux
# Require gettext-0.19.8
dist: focal
jobs:
  include:
  - name: "amd64"
    arch: amd64
  #- name: "ppc64le"
  #  arch: ppc64le
  #- name: "s390x"
  #  arch: s390x
  #- name: "arm64"
  #  arch: arm64
addons:
  apt:
    packages:
    - gnome-common
    - gtk-doc-tools
script:
  - git clone git://github.com/ibus/ibus.git
  - cd ibus
  - ./autogen.sh
