language: c
compiler: gcc
os: linux
# Require gettext-0.19.8
dist: focal
branches:
  only:
  - master
addons:
  apt:
    packages:
    # For autogen.sh
    - gnome-common
    - gtk-doc-tools
    # For make from
    # https://packages.ubuntu.com/search?searchon=sourcenames&keywords=ibus
    - desktop-file-utils
    - gobject-introspection
    - iso-codes
    - libdconf-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-bin
    - libgtk-3-dev
    - libgtk2.0-dev
    - libtool
    - libwayland-dev
    - python-gi-dev
    - python3-all
    - unicode-cldr-core
    - unicode-data
    - valac
jobs:
  include:
  - name: amd64
    arch: amd64
  - name: ppc64le
    arch: ppc64le
  - name: s390x
    arch: s390x
  - name: arm64
    arch: arm64
before_script:
- sudo apt-get -qq update
script:
- set -e
- git clone git://github.com/ibus/ibus.git
- cd ibus
- patch -p1 < ../.github/0001-engine-Fix-iso-path-in-gensimple.py.patch
- patch -p1 < ../.github/0002-engine-Fix-input-in-gensimple.py.patch
# https://salsa.debian.org/debian/ibus/-/blob/master/debian/rules
- >
  ./autogen.sh
  --with-ucd-dir='/usr/share/unicode'
# Set the cutom DESTDIR because the default DESTDIR
# /home/travis/bulid/fujiwarat/$PKG/ibus/ibus-$VERSION/_inst seems to be
# too long and failed to set DESTDIR to install bindings/pygobject/IBus.py
- >
  make distcheck
  DISTCHECK_CONFIGURE_FLAGS="
  --enable-gtk-doc
  --disable-schemas-install
  --enable-memconf
  --with-ucd-dir='/usr/share/unicode'
  "
  DISABLE_GUI_TESTS="ibus-compose ibus-keypress test-stress"
  VERBOSE=1
  DESTDIR="$HOME/build/$USER/dest"
