language: c
compiler: gcc
os: linux
# Require gettext-0.19.8
dist: focal
arch:
  - amd64
  #- ppc64le
  #- s390x
  #- arm64
addons:
  apt:
    packages:
    # For autogen.sh
    - gnome-common
    - gtk-doc-tools
    # For make from
    # https://packages.ubuntu.com/search?searchon=sourcenames&keywords=ibus
    - desktop-file-utils
    - gobject-introspection
    - iso-codes
    - libdconf-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-bin
    - libgtk-3-dev
    - libgtk2.0-dev
    - libtool
    - libwayland-dev
    - python-gi-dev
    - python3-all
    - unicode-cldr-core
    - unicode-data
    - valac
jobs:
  include:
  - name: Build
    before_script:
    - sudo apt-get -qq update
    script:
    - set -e
    - git clone git://github.com/ibus/ibus.git
    - cd ibus
    - patch -p1 < ../.github/0001-engine-Fix-iso-path-in-gensimple.py.patch
    - patch -p1 < ../.github/0002-engine-Fix-input-in-gensimple.py.patch
    # https://salsa.debian.org/debian/ibus/-/blob/master/debian/rules
    - >
      ./autogen.sh
      --with-ucd-dir='/usr/share/unicode'
    - make distcheck
