# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
        with:
          repository: ibus/ibus
          fetch-depth: 200

      # Runs a single command using the runners shell
      - name: Initialize
        run: |
          sudo apt-get -qq update
          echo "$INPUT_PACKAGES"
          #echo '${{ github.event.inputs.packages }}'
        with:
         packages: |
            # For autogen.sh
            autopoint
            # For make from
            # https://packages.ubuntu.com/search?searchon=sourcenames&keywords=ibus
            desktop-file-utils
            gobject-introspection
            gtk-doc-tools
            iso-codes
            libdconf-dev
            libgirepository1.0-dev
            libglib2.0-dev
            libgtk-3-bin
            libgtk-3-dev
            libgtk2.0-dev
            libnotify-dev
            libtool
            libwayland-dev
            python-gi-dev
            python3-all
            unicode-cldr-core
            unicode-data
            valac

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pwd
          ls -a ${{ github.workspace }}
          echo test, and deploy your project.
